# This is the included file for the main Makefile -- put your localization definitions here.
# But do not check in your changes to the repository. :D

# User compilers
# CC=icc
# CPP=icpc
# FC=ifort

# User compiling options 
# For reasonable speed, uncomment the following line; you may try -O3 instead of -O2.
# BOPT=-O2 -funroll-loops -ftree-vectorize

# Uncomment the following line to turn on OpenMP version
# BOPT+=-fopenmp

# User preprocessing definitions
# CDEFS+=xx
# FDEFS+=xx
