print "==============================================================="
print "Building FASP -- Target:", map(str, BUILD_TARGETS)
print "Sample Usage: "
print ">> scons -Q .             % Build all type of libraries        "
print ">> scons -Q target        % Build target (release,shared,debug)"
print ">> scons -Q target omp=1  % Build target with OpenMP support   "
print ">> scons -Q install       % Install all compiled libraries     "
print ">> scons -c target        % Clean up target obj files          "
print ">> scons -c .             % Clean up everything, distclean     "
print ">> scons -h               % Print usage and help               " 
print "==============================================================="

# SCons script for FASP
SConscript('fasp.scons')
