# SCons script for FASP
SConscript('fasp.scons')

# Output information ...
print "==============================================================="
print "  Building the FASP library -- Target:", map(str, BUILD_TARGETS)
print "==============================================================="
